set -g prefix C-s

# Truecolor support
set -sa terminal-features ',xterm-256color:RGB'
# Enable mouse support
set -g mouse on

# Start windows at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Move panels
bind -n C-S-M-Left swap-window -t -1 \;  previous-window
bind -n C-S-M-Right swap-window -t +1 \; next-window

# Vim-style pane navigation
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind r
bind r source-file ~/.tmux.conf

# Enter copy mode with prefix d
bind d copy-mode

# Copy to system clipboard (macOS)
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'

# Fluoromachine theme
set -g status-position top
set -g status-style "bg=#262335,fg=#8BA7A7"
set -g status-left "#[fg=#262335,bg=#FC199A,bold] #S #[fg=#FC199A,bg=#262335,nobold]  "
set -g status-right "#[fg=#61E2FF,bg=#262335] %H:%M  #[fg=#262335,bg=#61E2FF,bold] #H "
set -g status-left-length 40
set -g status-right-length 60
set -g window-status-format "#[fg=#495495,bg=#262335] #I:#W "
set -g window-status-current-format "#[fg=#262335,bg=#AF6DF9,bold] #I:#W #[fg=#AF6DF9,bg=#262335,nobold]"
set -g window-status-separator ""
set -g message-style "fg=#8BA7A7,bg=#463465"
set -g message-command-style "fg=#FC199A,bg=#463465"
set -g mode-style "fg=#262335,bg=#AF6DF9"
set -g pane-border-style "fg=#463465"
set -g pane-active-border-style "fg=#72F1B8"

# dim inactive windows
set -g focus-events on
setw -g window-active-style 'fg=#8BA7A7,bg=#241B2F'
setw -g window-style 'fg=#495495,bg=#262335'




# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
