-- snacks.picker keymaps (replaces telescope.nvim)
vim.keymap.set("n", "<leader>ff",  function() Snacks.picker.files() end,           { desc = "Find files" })
vim.keymap.set("n", "<leader>fg",  function() Snacks.picker.grep() end,            { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb",  function() Snacks.picker.buffers() end,         { desc = "Buffers" })
vim.keymap.set("n", "<leader>fh",  function() Snacks.picker.help() end,            { desc = "Help tags" })
vim.keymap.set("n", "<leader>fr",  function() Snacks.picker.command_history() end, { desc = "Command history" })
vim.keymap.set("n", "<leader>fc",  function() Snacks.picker.commands() end,        { desc = "Commands" })
